apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: client
          image: asia-southeast1-docker.pkg.dev/k8s-practice-416103/k8s-practice-registry/multi-client:latest
          ports:
            - containerPort: 3000
